# Generated by Django 5.2.4 on 2025-07-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('credits', models.FloatField()),
                ('type_cn', models.CharField(max_length=100)),
                ('gradation_cn', models.CharField(max_length=100)),
                ('category_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('classify_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_mode', models.CharField(max_length=200)),
                ('teach_lang', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.campus')),
                ('open_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('period', models.IntegerField()),
                ('periods_per_week', models.IntegerField()),
                ('std_count', models.IntegerField()),
                ('limit_count', models.IntegerField()),
                ('is_graduate_course', models.BooleanField()),
                ('date_time_place_text', models.TextField()),
                ('date_time_place_person_text', models.JSONField()),
                ('admin_classes', models.ManyToManyField(related_name='sections', to='timetable.adminclass')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('teachers', models.ManyToManyField(related_name='sections', to='timetable.teacher')),
            ],
        ),
    ]
