# Generated by Django 5.2.4 on 2025-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
