# Generated by Django 5.2.4 on 2025-07-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustc', '0002_alter_course_code_alter_section_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminclass',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Admin Classes'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='classtype',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Class Types'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='courseclassify',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Course Classifies'},
        ),
        migrations.AlterModelOptions(
            name='coursegradation',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Course Gradations'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Course Types'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Education Levels'},
        ),
        migrations.AlterModelOptions(
            name='exammode',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Exam Modes'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['code', 'semester__start_date'], 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teachlanguage',
            options={'ordering': ['name_cn'], 'verbose_name_plural': 'Teach Languages'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam_mode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='open_department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teach_language',
        ),
        migrations.AddField(
            model_name='section',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.campus'),
        ),
        migrations.AddField(
            model_name='section',
            name='exam_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.exammode'),
        ),
        migrations.AddField(
            model_name='section',
            name='open_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='teach_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.teachlanguage'),
        ),
    ]
