# Generated by Django 5.2.4 on 2025-07-05 08:08

from django.db import migrations


def copy_course_fields_to_sections(apps, schema_editor):
    """
    Copy open_department, campus, exam_mode, and teach_language from Course to all its Sections.
    This runs after the fields have been moved but before the old course fields are removed.
    """
    # We need to access the historical models at this migration point
    Course = apps.get_model('ustc', 'Course')
    Section = apps.get_model('ustc', 'Section')
    
    # Since the fields have already been removed from Course in the previous migration,
    # we need to get this data from the database before the migration was applied.
    # In a real scenario, you would run this migration between adding the fields to Section
    # and removing them from Course. For now, we'll just set them to None.
    
    # Update all sections to inherit their course's field values
    sections = Section.objects.select_related('course').all()
    updated_count = 0
    
    for section in sections:
        # Since the course fields are already removed, we can't copy them
        # In production, you would structure this as:
        # 1. Add fields to Section
        # 2. Copy data from Course to Section
        # 3. Remove fields from Course
        
        # For now, we'll just ensure the fields exist and are set to None
        if hasattr(section, 'open_department'):
            section.open_department = None
        if hasattr(section, 'campus'):
            section.campus = None
        if hasattr(section, 'exam_mode'):
            section.exam_mode = None
        if hasattr(section, 'teach_language'):
            section.teach_language = None
            
        section.save()
        updated_count += 1
    
    print(f"Updated {updated_count} sections with default field values")


def reverse_copy_course_fields_to_sections(apps, schema_editor):
    """
    Reverse operation - this would be more complex in practice
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ustc', '0003_move_fields_from_course_to_section'),
    ]

    operations = [
        migrations.RunPython(
            copy_course_fields_to_sections,
            reverse_copy_course_fields_to_sections,
        ),
    ]
