# Generated by Django 5.2.4 on 2025-07-31 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustc', '0004_copy_course_fields_to_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Room Types',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=20)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.campus')),
            ],
            options={
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jw_id', models.IntegerField(unique=True)),
                ('name_cn', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('virtual', models.BooleanField(default=False)),
                ('seats_for_section', models.IntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('seats', models.IntegerField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.building')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jw_id', models.IntegerField(unique=True)),
                ('no', models.IntegerField()),
                ('limit_count', models.IntegerField()),
                ('std_count', models.IntegerField()),
                ('actual_periods', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustc.section')),
            ],
            options={
                'verbose_name_plural': 'Schedule Groups',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.IntegerField()),
                ('date', models.DateField()),
                ('weekday', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('experiment', models.TextField(blank=True, null=True)),
                ('custom_place', models.TextField(blank=True, null=True)),
                ('lesson_type', models.TextField(blank=True, null=True)),
                ('week_index', models.IntegerField()),
                ('exercise_class', models.BooleanField(default=False)),
                ('start_unit', models.IntegerField()),
                ('end_unit', models.IntegerField()),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustc.section')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ustc.teacher')),
                ('schedule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ustc.schedulegroup')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
