# Generated by Django 5.2.4 on 2025-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustc', '0005_roomtype_teacher_person_id_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='jw_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='jw_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
