# Generated by Django 5.2.4 on 2025-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustc', '0006_building_jw_id_roomtype_jw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='jw_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
